In [17]:
import torch
import numpy as np

In [4]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [9]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
torch.randn(2,3,4)

tensor([[[ 0.9162, -0.3267, -0.9757, -0.0547],
         [ 1.6223, -0.2072, -1.4681,  0.2148],
         [ 0.5197,  0.5365, -1.3659,  0.1021]],

        [[ 0.5341,  1.0043, -0.6829,  0.8488],
         [-0.4506,  1.1426,  0.2231,  0.2639],
         [ 0.5600,  0.7169, -0.2426,  0.2121]]])

In [15]:
torch.tensor([[1,2,3,4],[2,3,4,1],[2,3,4,1]])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 1],
        [2, 3, 4, 1]])

In [22]:
x = torch.tensor([1.0,2,3])
y = torch.tensor([2,3,4])
x + y, x - y, x * y, x / y

(tensor([3., 5., 7.]),
 tensor([-1., -1., -1.]),
 tensor([ 2.,  6., 12.]),
 tensor([0.5000, 0.6667, 0.7500]))

In [23]:
torch.exp(x)

tensor([ 2.7183,  7.3891, 20.0855])

In [25]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),0), torch.cat((X,Y),1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [26]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [27]:
X.sum()

tensor(66.)

In [28]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
X,X[-1],X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [30]:
X[1,2]

tensor(6.)

In [32]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [36]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [37]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x+y, x*y,x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [39]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [40]:
x[3]

tensor(3)

In [41]:
len(x)

4

In [42]:
x.shape

torch.Size([4])

In [43]:
a.T

tensor([3.5000])

In [51]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
A, A.sum(axis=0), A.sum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([40., 45., 50., 55.]),
 tensor([ 6., 22., 38., 54., 70.]))

In [52]:
A.sum(axis=[0,1])

tensor(190.)

In [53]:
A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [54]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [56]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 6.],
         [22.],
         [38.],
         [54.],
         [70.]]), torch.Size([5, 1]))

In [57]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [59]:
y = np.ones(4)
x, y , np.dot(x,y)

(tensor([0, 1, 2, 3]), array([1., 1., 1., 1.]), 6.0)

In [63]:
A.shape, x.shape, torch.mm(A,x)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [65]:
B = torch.ones(4,3)
A.shape, B.shape,torch.mm(A,B)

(torch.Size([5, 4]), torch.Size([4, 3]), tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [66]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [67]:
torch.abs(u).sum()

tensor(7.)

In [71]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [73]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [76]:
import torch
y = 2 * torch.dot(x, x)

In [78]:
y.backward()

In [79]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [80]:
x.grad == 4*x

tensor([True, True, True, True])

In [81]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

tensor([1., 1., 1., 1.])

In [86]:
x.grad.zero_()
y = x*x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [88]:
x.grad.zero_()
y.sum().backward()
x.grad == 2*x

tensor([True, True, True, True])

In [89]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [90]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [92]:
a.grad == d/a

tensor(True)

In [95]:
a

tensor(-1.0866, requires_grad=True)

In [96]:
print(dir(torch.distributions))

['AbsTransform', 'AffineTransform', 'Bernoulli', 'Beta', 'Binomial', 'CatTransform', 'Categorical', 'Cauchy', 'Chi2', 'ComposeTransform', 'Dirichlet', 'Distribution', 'ExpTransform', 'Exponential', 'ExponentialFamily', 'FisherSnedecor', 'Gamma', 'Geometric', 'Gumbel', 'HalfCauchy', 'HalfNormal', 'Independent', 'Laplace', 'LogNormal', 'LogisticNormal', 'LowRankMultivariateNormal', 'LowerCholeskyTransform', 'Multinomial', 'MultivariateNormal', 'NegativeBinomial', 'Normal', 'OneHotCategorical', 'Pareto', 'Poisson', 'PowerTransform', 'RelaxedBernoulli', 'RelaxedOneHotCategorical', 'SigmoidTransform', 'SoftmaxTransform', 'StackTransform', 'StickBreakingTransform', 'StudentT', 'Transform', 'TransformedDistribution', 'Uniform', 'Weibull', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'bernoulli', 'beta', 'biject_to', 'binomial', 'categorical', 'cauchy', 'chi2', 'constraint_registry', 'constraints', 'dirichlet',

In [97]:
help(torch.ones)

Help on built-in function ones:

ones(...)
    ones(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with the scalar value `1`, with the shape defined
    by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None``, uses the current device for the default ten

In [98]:
torch.ones(4)

tensor([1., 1., 1., 1.])